apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: springbootdockerapp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: springbootdockerapp
    spec:
      containers:
        - name: springbootdockerapp
          image: springbootdockerapp
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: springbootdockerapp
  labels:
    name: springbootdockerapp
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: springbootdockerapp
  type: NodePort
